// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvggdSUSkXohXov0cC0xWoV-Bs9jjMdg',
    appId: '1:867054067354:web:c467106ebeecb15d160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    authDomain: 'ecommercestore-203d7.firebaseapp.com',
    storageBucket: 'ecommercestore-203d7.appspot.com',
    measurementId: 'G-1X40RCENME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWwmImm4t2cpklqAB2ukHitmPvWZ7BJM',
    appId: '1:867054067354:android:af624b9267da5025160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtFr51jaYeduNdCFLS1LRTVLUeUcuBOHc',
    appId: '1:867054067354:ios:07de5047c78f8d88160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.appspot.com',
    iosBundleId: 'com.example.ecommercestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtFr51jaYeduNdCFLS1LRTVLUeUcuBOHc',
    appId: '1:867054067354:ios:07de5047c78f8d88160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    storageBucket: 'ecommercestore-203d7.appspot.com',
    iosBundleId: 'com.example.ecommercestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbvggdSUSkXohXov0cC0xWoV-Bs9jjMdg',
    appId: '1:867054067354:web:1d43cbd0c762dcf4160923',
    messagingSenderId: '867054067354',
    projectId: 'ecommercestore-203d7',
    databaseURL: 'https://ecommercestore-203d7-default-rtdb.firebaseio.com',
    authDomain: 'ecommercestore-203d7.firebaseapp.com',
    storageBucket: 'ecommercestore-203d7.appspot.com',
    measurementId: 'G-3VVCMKS391',
  );
}
